export const products = [
  {
    id: 1,
    name: 'Egg Chicken Red',
    description: '4pcs',
    price: 1.99,
    image: require('../assets/egg_red.png'),
    category: 'eggs',
  },
  {
    id: 2,
    name: 'Egg Chicken White',
    description: '180g',
    price: 1.50,
    image: require('../assets/egg_white.png'),
    category: 'eggs',
  },
  {
    id: 3,
    name: 'Egg Pasta',
    description: '30gm',
    price: 15.99,
    image: require('../assets/egg_pasta.png'),
    category: 'pasta',
  },
  {
    id: 4,
    name: 'Egg Noodles',
    description: '2L',
    price: 15.99,
    image: require('../assets/egg_noodles.png'),
    category: 'noodles',
  },
  {
    id: 5,
    name: 'Mayonnais Eggless',
    description: '200ml',
    price: 3.99,
    image: require('../assets/mayo.png'),
    category: 'condiments',
  },
  {
    id: 6,
    name: 'Egg Noodles',
    description: '500g',
    price: 2.99,
    image: require('../assets/egg_noodles2.png'),
    category: 'noodles',
  },
];